### ISSUE TITLE
Разобраться как давать ссылки на файлы на нашем же сайте

### ISSUE THREAD

**Issue by Natasay** [quarteera/www.quarteera.de#10]
Например, в разделе "Миграция" ссылки на памятки, в разделе "Стать членом" на файл про членство и пр.

**Comment by artjomusp** [comment]
Статические файлы выкладываются в папку "static" (можно в подпапки) ссылки на файл делаются так:

`[форму заявления](/Mitgliedschaftsantrag.pdf).`

в этой ситуации файл на всех языках один и тот же. если нужны разные файлы, то стоит создать подпапки.

ссылки на членство и пожертвования я настроил.
