### ISSUE TITLE
Шаблон "О нас". Нет возможности добавить текст над блоками подразделов

### ISSUE THREAD

**Issue by Natasay** [quarteera/www.quarteera.de#12]
https://deploy-preview-6--quarteera-site-dev.netlify.app/about/
В этом шаблоне отображается только текст из summary.
Текст в шаблоне не отображается на странице видимо из-за ошибки в верстке: 

---
RU „Разнообразие heißt Vielfalt“ это типовой проект в рамках программы «Модернизация и развитие структур гражданского образования для взрослых – усиление и диверсификация» Федерального агентства по гражданскому образованию. Провышение квалификации русскоязычных активист_ок в сфере гражданского образования с целью поддержки и развития русскоязычного ЛГБТИК+ сообщества в Германии. Мы хотим предоставить активист_кам возможность самостоятельно повышать осведомленность общества о своих интересах, создавать устойчивые общественные структуры и профессионально работать в сфере гражданского образования. Основным направлением проекта является повышение осведомлённости о сексуальных и гендерных идентичностях среди русскоговорящего населения Германии.

**Comment by artjomusp** [comment]
fixed by #13
